# MoveGroup specific configuration
planning_scene_monitor:
  publish_planning_scene: true
  publish_geometry_updates: true
  publish_state_updates: true
  publish_transforms_updates: true

# Default planning time (in seconds)
default_planning_time: 5.0

# Default goal tolerance
default_goal_tolerance: 0.01

# Default goal joint tolerance (in radians)
default_goal_joint_tolerance: 0.01

